// We Will Use open() & eof() function Instread Of Constructor Of fstream.....
// We Will Use Multiple Files & More Than One File At A Time.....
#include<iostream>
#include<fstream>
#include<string.h>
using  namespace std;

int main(){
    ofstream output ;
    ifstream input1 , input2 , input3;

    //Applying Output Stream In The File 'Temp37_Part1.txt'......
    output.open("Temp37_Part1.txt");  // Connect File With Object 'output'.......
    string str1="Prabhash Pandey \nAnnu Pandey \nIsha Pandey \nAradhya Pandey \nAtrarva Pandey";
    output<<str1;
    str1.clear();   //Inbuilt Method To Clear A String.......
    output.close();   // Dis-Connect File From Object 'output'.......
    
    //Applying Output Stream In The File 'Temp37_Part2.txt'......
    output.open("Temp37_Part2.txt");  // Connect File With Object 'output'.......
    string str2="Hira Lal Pandey \nNarendra Pandey \nPrabhash Pandey \nAnil Pandey \nAmit Pandey";
    output<<str2;
    str2.clear();   //Inbuilt Method To Clear A String.......
    output.close();   // Dis-Connect File From Object 'output'.......
    
    //Applying Output Stream In The File 'Temp37_Part3.txt'......
    output.open("Temp37_Part3.txt");  // Connect File With Object 'output'.......
    string str3="Prem Pandey \nVidya Pandey \nAnnu Pandey \nPriyanka Pandey \nSonam Pandey";
    output<<str3;
    str3.clear();   //Inbuilt Method To Clear A String.......
    output.close();   // Dis-Connect File From Object 'output'.......

    //Applying Input Stream In All 3 Files.......
    input1.open("Temp37_Part1.txt");
    input2.open("Temp37_Part2.txt");
    input3.open("Temp37_Part3.txt");
    while(input1.eof()==0){
        getline(input1,str1); 
        getline(input2,str2); 
        getline(input3,str3);
        cout<<"PARENTS OF '"<<str1<<"' ARE 'Mr."<<str2<<"' & 'Mrs."<<str3<<"'"<<endl;
        str1.clear();   //Inbuilt Method To Clear A String.......
        str2.clear();   //Inbuilt Method To Clear A String.......
        str3.clear();   //Inbuilt Method To Clear A String.......
    }
    input1.close();
    input2.close();
    input3.close();

    return 0;
}