// We Will Use open() & eof() function Instread Of Constructor Of fstream.....
// We Will Use Multiple Files But 1 File At A Time.....
#include<iostream>
#include<fstream>
#include<string.h>
using namespace std;

int main(){
    ofstream output;  //'output' Is Object Of InBuilt Class ofstream In HeaderFile->fstream.......
    ifstream input;   //'input' Is Object Of InBuilt Class ifstream In HeaderFile->fstream.......

    //Applying Output Stream In The File 'Temp36_Part1.txt'......
    output.open("Temp36_Part1.txt");  // Connect File With Object 'output'.......
    string str1="Hello I Am Yash Pandey \nI Am 20 Years Old \nI Am In 2nd Year Of B.Tech";
    output<<str1;
    output.close();   // Dis-Connect File From Object 'output'.......
    
    //Applying Output Stream In The File 'Temp36_Part2.txt'......
    output.open("Temp36_Part2.txt");  // Connect File With Object 'output'.......
    string str2="Hello I Am Isha Pandey \nI Am 18 Years Old \nI Am In 1st Year Of B.Tech";
    output<<str2;
    output.close();   // Dis-Connect File From Object 'output'.......

    //Applying Input Stream In The File 'Temp36_Part1.txt'......
    cout<<"DATA IN FILE 'Temp36_Part1.txt' IS ::: "<<endl;
    input.open("Temp36_Part1.txt");  // Connect File With Object 'input'.......
    string str3;
    while(input.eof()==0){  //If File Ends , Then , eof() Will Return 1......
        getline(input,str3);
        cout<<str3<<endl;
        str3.clear();  //Inbuilt Method To Clear A String.......
    }
    cout<<endl;
    input.close();   // Dis-Connect File From Object 'input'.......
    
    //Applying Input Stream In The File 'Temp36_Part2.txt'......
    cout<<"DATA IN FILE 'Temp36_Part2.txt' IS ::: "<<endl;
    input.open("Temp36_Part2.txt");  // Connect File With Object 'input'.......
    string str4;
    while(input.eof()==0){  //If File Ends , Then , eof() Will Return 1......
        getline(input,str4);
        cout<<str4<<endl;
        str4.clear();  //Inbuilt Method To Clear A String.......
    }
    cout<<endl;
    input.close();   // Dis-Connect File From Object 'input'.......
    
    return 0;
}